version: "3"

services:
  web:
    build:
      context: ./web/
    ports:
      - "8000:8000"
    links:
      - redis
      - nginx

  redis:
    build:
      context: ./redis/
    restart: always
    ports:
      - 6379:6379

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
