version: "3"

services:
  web:
    build:
      context: ./web/
    ports:
      - "8000:8000"
    links:
      - redis
      - nginx

  redis:
    image: redis:buster

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
